// Ryan's Algorithms 
// This is Ryan Riesenberger's massive algo collection //
// These algos are alphabetically sorted //
console.warn('Ryans algos is working from the beginning...');

//aBCheck
//acronym
//addCommas
//additivePersistence
//addMe
//addRandomCharacters
//anagram
//arithGeo
//arrayAddition
//arrayStats
//averageInteger
//averageArray
//averageFirstInArray
//balanceParens
//binaryAgent
//booWho
//bouncer (falsyBouncer)
//caesarsCipher
//callThisWithThat
//camelCase
//capitalizeLastName
//capper (capFirstLetter)
//characterFrequent
//checkBoolean
//checkFunction
//checkNumber
//checkPrime
//checkString
//chunkArrayInGroups
//circleOrSquare
//computeAverage
//confirmEnding
//consonantCount
//convertHTML
//convertToCels
//convertToFahr
//convertToRanges
//convertToRoman
//countByIncrement
//countingCards
//countDown
//crazyReverse
//curve
//dashInsert
//dashInsert2
//destroyer
//difference
//diffArray
//disemVoweler
//distanceFromMiddle
//diveAndDelete
//divisionStringified
//DNAElement
//doubleTheMutable
//duplicator
//duplicateFinder
//eradicateB
//exclamation
//exponentPower
//exOh
//evenOccurence
//evenSum
//factorialize
//fibonacci
//findElement
//findLongestWord
//findSolution
//firstNonRepeatingCharacter
//flipAndUp
//frequency
//getIndexToIns (whereDoIBelong)
//getAtPosition
//getMiddle
//getNumber
//getRandomWords
//golfScore
//greatestCommonDivisor
//hexMeRandom
//higherOrLower
//howManyWords
//indexOfFirstWord
//insertHere
//intersection
//isDeepEqual
//isOdd
//largestOfFour
//letterChanges
//letterCount
//lonelyInteger
//longestWord
//magic8Ball
//maxProductOfTwoNumsDivisibleByThree
//miniArrays
//missingLetter
//mostSimilarLettersInWord
//mostVowels
//moveZeros
//multiplicativePersistence
//mutation
//nines
//ninesPartTwo
//nums2hex
//oddEvenSort
//ordinalEnding (st, nd rd, th)
//palindrome
//pairs
//permutations
//pigLatin
//powersOfTwo
//primeFactors
//randomNum
//randomGen
//randomNumberInRange
//randomPointGenerator
//randomWordInSentence
//range
//removeAll
//removeDuplicates
//remove Index
//removeX
//removeVowels
//repeatedLetter
//repeatStringNumTimes
//replaceBigE
//reverseCase
//reverseEveryOther
//reverseInPlace
//reverseString
//salesTax
//scrabble
//searchAndReplace
//secondToLast
//secondGreatLow
//sentenceBreak
//shortestWord
//shuffleString
//slashed
//slug
//splitSum
//spinalCase
//smallestCommons
//steamRollArray (flatten)(squishy)
//submarineObjecter
//subStringFinder
//sortedVowels
//sortEm
//squishy (steamRollArray)(flatten)
//stringMutation
//stripCamelCase
//sumAll
//sumFinder
//sumOddFibonacciNums
//sumOddSumEven
//sumAllPrimes
//superSort
//swapCase
//switcher
//telephoneCheck
//thirdLongest
//timeConvert
//timesTable
//timeTraveler
//titleCase
//translate
//tripleZeros
//truncateString
//truthCheck
//unCamelCase
//uniteUnique (Sorted Union)
//unMixString
//upperCaser
//validateDate
//vowelCount
//wheresWaldo

//RECURSION:
//additivePersistenceRecursive
//diveAndDeleteRec
//exponentPowerRecursive
//fibbonaciRecursive
//findSolutionRecursive
//firstFactorialRecursive
//flattenObjectsRecursive
//flattenRecursive
//greatestCommonnDenominatorRecursive
//multiplicativePersistenceRecursive
//multRecursive
//truthyCheckRecursively
//sumRecursive
